-- Truncate all tables for clean re-import
TRUNCATE TABLE exam_assignments RESTART IDENTITY CASCADE;
TRUNCATE TABLE assignment_questions RESTART IDENTITY CASCADE;
TRUNCATE TABLE vocabulary_lessons RESTART IDENTITY CASCADE;
TRUNCATE TABLE exams RESTART IDENTITY CASCADE;
TRUNCATE TABLE assignments RESTART IDENTITY CASCADE;
TRUNCATE TABLE questions RESTART IDENTITY CASCADE;
